language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libaa1
cache:
  directories:
  - $HOME/.cache
install:
- pip install --upgrade pip
- pip install python-aalib
- pip install pillow
- pip install pyflakes
- pip install docutils pygments
script:
- ./abdicate --help
- private/run-pyflakes
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
