dist: trusty
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libaa1
cache: pip
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install python-aalib
- python3 -m pip install pillow
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install restructuredtext-lint pygments
script:
- ./abdicate --help
- python3 -m pyflakes abdicate
- python3 -m pydiatra abdicate
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
