name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.3'
          os: ubuntu-18.04
        - python: '3.4'
          os: ubuntu-18.04
        - python: '3.5'
          os: ubuntu-18.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: install python-aalib
      run: |
        sudo apt-get install libaa1
        python3 -m pip install python-aalib
    - name: install Pillow
      run: |
        pillow=pillow
        if [[ ${{matrix.python}} = 3.3 ]]; then pillow+='<6'; fi
        python3 -m pip install $pillow
    - name: smoke test
      run: |
        ./abdicate --help
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra abdicate
    - name: run pyflakes
      run: |
        pyflakes=pyflakes
        if [[ ${{matrix.python}} = 3.3 ]]; then pyflakes+='<2'; fi
        pip install $pyflakes
        python3 -m pyflakes abdicate
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint abdicate
      if:
        matrix.python != '3.3' &&
        matrix.python != '3.4'
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
